cars = []
cars.append('lamba')
cars.append('honda')
cars.append('bmw')
cars.append('suzuki')
cars.append('ferrari')
cars.append('cherry')
print(cars)
cars.insert(4,'lada')
del cars[4]
print(cars)
del_item = cars.pop(3)
print(cars)
print(del_item)
cars.remove('suzuki')
